server {
    listen 80;

    root /usr/share/nginx/html;

    index index.html;

    location = / {
        return 301 /identity_journey/;
    }

    location /identity_journey/ {
        try_files $uri $uri/ /identity_journey/index.html;
    }

    error_page 404 /identity_journey/index.html;
}
