server {
    listen 80;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location = / {
        return 301 /identity_journey/;
    }

    location /identity_journey/ {
        alias /usr/share/nginx/html/identity_journey/;
        index index.html;
        try_files $uri $uri/ /identity_journey/index.html;
    }

    error_page 404 /identity_journey/index.html;
}
