server {
    listen 80;

    root /usr/share/nginx/html;

    index index.html;

    location = / {
        return 301 /identity_journey/;
    }

    location /identity_journey/ {
        try_files $uri $uri/ /identity_journey/index.html;
    }

    location /api/ {
        proxy_pass http://localhost:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    error_page 404 /identity_journey/index.html;
}
